package service

import (
	"context"
	"crypto/tls"
	"fmt"
	"net/smtp"
	"strings"
	"time"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
	"github.com/atm-ucak/follup/internal/domain"
	"github.com/atm-ucak/follup/internal/infra"
	"github.com/atm-ucak/follup/internal/repository"
)

// EmailServiceImpl implements the EmailService interface
type EmailServiceImpl struct {
	emailRepo      repository.EmailCredentialRepository
	automationRepo repository.AutomationRuleRepository
	threadRepo     repository.EmailThreadRepository
	jiraService    JiraService
	config         *domain.Config
}

// NewEmailService creates a new EmailService instance
func NewEmailService(
	emailRepo repository.EmailCredentialRepository,
	automationRepo repository.AutomationRuleRepository,
	threadRepo repository.EmailThreadRepository,
	jiraService JiraService,
	config *domain.Config,
) EmailService {
	return &EmailServiceImpl{
		emailRepo:      emailRepo,
		automationRepo: automationRepo,
		threadRepo:     threadRepo,
		jiraService:    jiraService,
		config:         config,
	}
}

// SaveCredential saves email credentials with encryption
func (s *EmailServiceImpl) SaveCredential(ctx context.Context, userID, email, password string) error {
	// Encrypt password using AES-256-GCM
	encryptedPassword, err := infra.Encrypt(password, []byte(s.config.AESSecretKey))
	if err != nil {
		return fmt.Errorf("failed to encrypt password: %w", err)
	}

	// Create EmailCredential entity
	cred := &domain.EmailCredential{
		UserID:            userID,
		EmailAddress:      email,
		EncryptedPassword: encryptedPassword,
		IMAPHost:          s.config.IMAPHost,
		SMTPHost:          s.config.SMTPHost,
		CreatedAt:         time.Now(),
	}

	// Save to repository
	if err := s.emailRepo.Create(ctx, cred); err != nil {
		return fmt.Errorf("failed to save credentials: %w", err)
	}

	return nil
}

// SendFollowUpByAutomation sends a follow-up email based on automation ID
func (s *EmailServiceImpl) SendFollowUpByAutomation(ctx context.Context, automationID string) error {
	// Get automation rule by ID
	automation, err := s.automationRepo.GetByID(ctx, automationID)
	if err != nil {
		return fmt.Errorf("failed to get automation rule: %w", err)
	}

	// Get email credential for user
	cred, err := s.emailRepo.GetByUserID(ctx, automation.UserID)
	if err != nil {
		return fmt.Errorf("failed to get email credentials: %w", err)
	}

	// Decrypt password
	password, err := s.DecryptPassword(cred.EncryptedPassword)
	if err != nil {
		return fmt.Errorf("failed to decrypt password: %w", err)
	}

	// Get Jira ticket details for context
	jiraIssue, err := s.jiraService.GetIssue(ctx, automation.UserID, automation.JiraTicketKey)
	if err != nil {
		return fmt.Errorf("failed to get Jira issue: %w", err)
	}

	// Compose email body with ticket info
	subject := fmt.Sprintf("Follow-up: %s", jiraIssue.Summary)
	body := s.composeEmailBody(*jiraIssue, automation)

	// Connect to SMTP (STARTTLS)
	if err := s.sendEmail(cred.EmailAddress, password, cred.SMTPHost, subject, body, automation.Recipients); err != nil {
		return fmt.Errorf("failed to send email: %w", err)
	}

	// Create EmailThread record
	thread := &domain.EmailThread{
		ID:           "", // Will be generated by repository
		UserID:       automation.UserID,
		AutomationID: automation.ID,
		GmailThreadID: "", // Will be set when we receive the message ID
		TicketID:     automation.JiraTicketID,
		Status:       domain.EmailThreadStatusOpen,
		LastSyncedAt: time.Now(),
	}

	if err := s.threadRepo.Create(ctx, thread); err != nil {
		return fmt.Errorf("failed to create email thread: %w", err)
	}

	// Update automation last run time
	now := time.Now()
	automation.LastRunAt = &now
	if err := s.automationRepo.Update(ctx, automation); err != nil {
		return fmt.Errorf("failed to update automation: %w", err)
	}

	return nil
}

// PollInbox polls IMAP inbox for replies
func (s *EmailServiceImpl) PollInbox(ctx context.Context) error {
	// Get all active automation rules
	activeAutomations, err := s.automationRepo.GetActiveRules(ctx)
	if err != nil {
		return fmt.Errorf("failed to get active automations: %w", err)
	}

	// Group automations by user to avoid redundant credential lookups
	userAutomations := make(map[string][]*domain.AutomationRule)
	for _, automation := range activeAutomations {
		userAutomations[automation.UserID] = append(userAutomations[automation.UserID], automation)
	}

	// Process each user's inbox
	for userID, automations := range userAutomations {
		if err := s.processUserInbox(ctx, userID, automations); err != nil {
			// Log error but continue processing other users
			fmt.Printf("Error processing user %s inbox: %v\n", userID, err)
		}
	}

	return nil
}

// processUserInbox processes a single user's inbox for replies
func (s *EmailServiceImpl) processUserInbox(ctx context.Context, userID string, automations []*domain.AutomationRule) error {
	// Get email credential
	cred, err := s.emailRepo.GetByUserID(ctx, userID)
	if err != nil {
		return fmt.Errorf("failed to get credentials: %w", err)
	}

	// Decrypt password
	password, err := s.DecryptPassword(cred.EncryptedPassword)
	if err != nil {
		return fmt.Errorf("failed to decrypt password: %w", err)
	}

	// Connect to IMAP
 imapClient, err := s.connectIMAP(cred.IMAPHost, cred.EmailAddress, password)
	if err != nil {
		return fmt.Errorf("failed to connect to IMAP: %w", err)
	}
	defer imapClient.Close()

	// Select INBOX
	mbox, err := imapClient.Select("INBOX", false)
	if err != nil {
		return fmt.Errorf("failed to select INBOX: %w", err)
	}

	// Fetch unseen messages
	if mbox.Messages == 0 {
		return nil // No messages to process
	}

	// Search for unseen messages
	criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{imap.SeenFlag}
	ids, err := imapClient.Search(criteria)
	if err != nil {
		return fmt.Errorf("failed to search messages: %w", err)
	}

	if len(ids) == 0 {
		return nil // No unseen messages
	}

	// Fetch message headers for thread matching
	seqset := new(imap.SeqSet)
	seqset.AddNum(ids...)

	messages := make(chan *imap.Message, len(ids))
	err = imapClient.Fetch(seqset, []imap.FetchItem{imap.FetchBody}, messages)
	if err != nil {
		return fmt.Errorf("failed to fetch messages: %w", err)
	}

	// Process messages and match to threads
	for msg := range messages {
		if err := s.processMessage(ctx, msg, userID); err != nil {
			fmt.Printf("Error processing message: %v\n", err)
		}
	}

	return nil
}

// processMessage processes a single message and tries to match it to a thread
func (s *EmailServiceImpl) processMessage(ctx context.Context, msg *imap.Message, userID string) error {
	// Extract headers for thread matching
	var messageID, inReplyTo, references string

	if msg.Envelope != nil {
		messageID = msg.Envelope.MessageId
		// Note: InReplyTo and References handling would be here
		// For now, we'll just use the message ID
	}

	// Try to match message to existing thread
	thread, err := s.matchMessageToThread(ctx, messageID, inReplyTo, references, userID)
	if err != nil {
		return fmt.Errorf("failed to match message to thread: %w", err)
	}

	// If thread found, update status to replied
	if thread != nil {
		thread.Status = domain.EmailThreadStatusReplied
		thread.LastSyncedAt = time.Now()
		if err := s.threadRepo.Update(ctx, thread); err != nil {
			return fmt.Errorf("failed to update thread status: %w", err)
		}
	}

	return nil
}

// matchMessageToThread matches a message to an existing thread using headers
func (s *EmailServiceImpl) matchMessageToThread(ctx context.Context, messageID, inReplyTo, references, userID string) (*domain.EmailThread, error) {
	// Try to match by In-Reply-To header first
	if inReplyTo != "" {
		thread, err := s.threadRepo.GetByGmailThreadID(ctx, inReplyTo)
		if err == nil && thread != nil && thread.UserID == userID {
			return thread, nil
		}
	}

	// Try to match by References header
	if references != "" {
		refIDs := strings.Split(references, " ")
		for _, refID := range refIDs {
			thread, err := s.threadRepo.GetByGmailThreadID(ctx, refID)
			if err == nil && thread != nil && thread.UserID == userID {
				return thread, nil
			}
		}
	}

	// Try to match by Message-ID (in case this is a direct reply)
	if messageID != "" {
		thread, err := s.threadRepo.GetByGmailThreadID(ctx, messageID)
		if err == nil && thread != nil && thread.UserID == userID {
			return thread, nil
		}
	}

	return nil, nil
}

// Helper methods

// DecryptPassword decrypts an encrypted password
func (s *EmailServiceImpl) DecryptPassword(encryptedPassword string) (string, error) {
	decrypted, err := infra.Decrypt(encryptedPassword, []byte(s.config.AESSecretKey))
	if err != nil {
		return "", fmt.Errorf("failed to decrypt password: %w", err)
	}
	return decrypted, nil
}

// connectIMAP connects to IMAP server and authenticates
func (s *EmailServiceImpl) connectIMAP(host, email, password string) (*client.Client, error) {
	// Connect to IMAP server
 imapClient, err := client.DialTLS(fmt.Sprintf("%s:993", host), &tls.Config{
		InsecureSkipVerify: false, // Use proper TLS verification in production
	})
	if err != nil {
		return nil, fmt.Errorf("failed to connect: %w", err)
	}

	// Authenticate
	if err := imapClient.Login(email, password); err != nil {
		imapClient.Close()
		return nil, fmt.Errorf("failed to authenticate: %w", err)
	}

	return imapClient, nil
}

// sendEmail sends an email using SMTP with STARTTLS
func (s *EmailServiceImpl) sendEmail(from, password, host, subject, body string, to []string) error {
	// Parse SMTP host
	parts := strings.Split(host, ":")
	smtpHost := parts[0]
	smtpPort := "587" // Default STARTTLS port

	if len(parts) > 1 {
		smtpPort = parts[1]
	}

	// Create email message
	msg := fmt.Sprintf("From: %s\r\nTo: %s\r\nSubject: %s\r\n\r\n%s",
		from,
		strings.Join(to, ", "),
		subject,
		body,
	)

	// Split recipients for individual validation
	var recipients []string
	for _, addr := range to {
		if addr != "" {
			recipients = append(recipients, addr)
		}
	}

	// Connect to SMTP server and send
	auth := smtp.PlainAuth("", from, password, smtpHost)
	err := smtp.SendMail(
		fmt.Sprintf("%s:%s", smtpHost, smtpPort),
		auth,
		from,
		recipients,
		[]byte(msg),
	)

	if err != nil {
		return fmt.Errorf("failed to send email: %w", err)
	}

	return nil
}

// composeEmailBody creates the email body with Jira ticket context
func (s *EmailServiceImpl) composeEmailBody(jiraIssue domain.JiraIssue, automation *domain.AutomationRule) string {
	return fmt.Sprintf(`Hello,

This is a follow-up regarding the Jira ticket: %s

Summary: %s
Status: %s
Stakeholders: %s

Please review and take appropriate action.

Best regards`,
		automation.JiraTicketKey,
		jiraIssue.Summary,
		jiraIssue.Status,
		strings.Join(jiraIssue.Stakeholders, ", "),
	)
}

// Legacy interface methods (for compatibility)

// RegisterCredential registers or updates email credentials
func (s *EmailServiceImpl) RegisterCredential(ctx interface{}, cred *domain.EmailCredential) error {
	contextCast, ok := ctx.(context.Context)
	if !ok {
		return fmt.Errorf("invalid context type")
	}

	if cred.EmailAddress == "" {
		return fmt.Errorf("email address is required")
	}
	// Check if credential already exists
	existingCred, err := s.emailRepo.GetByUserID(contextCast, cred.UserID)
	if err != nil {
		// Credential doesn't exist, create new one
		return s.emailRepo.Create(contextCast, cred)
	}
	// Credential exists, update it
	cred.CreatedAt = existingCred.CreatedAt // Preserve creation time
	return s.emailRepo.Update(contextCast, cred)
}

// GetCredential retrieves email credentials for a user
func (s *EmailServiceImpl) GetCredential(ctx interface{}, userID string) (*domain.EmailCredential, error) {
	contextCast, ok := ctx.(context.Context)
	if !ok {
		return nil, fmt.Errorf("invalid context type")
	}
	return s.emailRepo.GetByUserID(contextCast, userID)
}

// SendFollowUp sends a follow-up email
func (s *EmailServiceImpl) SendFollowUp(ctx interface{}, threadID, subject, body string, recipients []string) error {
	// This is a placeholder for the legacy interface method
	return fmt.Errorf("not implemented: use SendFollowUpByAutomation instead")
}

// CheckForReplies checks IMAP for replies to sent emails
func (s *EmailServiceImpl) CheckForReplies(ctx interface{}) error {
	contextCast, ok := ctx.(context.Context)
	if !ok {
		return fmt.Errorf("invalid context type")
	}
	return s.PollInbox(contextCast)
}