package service

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/tls"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"net/smtp"
	"strings"
	"time"

	"github.com/atm-ucak/follup/internal/domain"
	"github.com/atm-ucak/follup/internal/infra"
	"github.com/atm-ucak/follup/internal/repository"
	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
	"github.com/google/uuid"
)

// EmailServiceImpl implements the EmailService interface
type EmailServiceImpl struct {
	emailRepo    repository.EmailCredentialRepository
	followupRepo repository.FollowupRepository
	threadRepo   repository.EmailThreadRepository
	config       *domain.Config
}

// NewEmailService creates a new EmailService instance
func NewEmailService(
	emailRepo repository.EmailCredentialRepository,
	followupRepo repository.FollowupRepository,
	threadRepo repository.EmailThreadRepository,
	config *domain.Config,
) EmailService {
	return &EmailServiceImpl{
		emailRepo:    emailRepo,
		followupRepo: followupRepo,
		threadRepo:   threadRepo,
		config:       config,
	}
}

// SaveCredential saves email credentials with encryption
func (s *EmailServiceImpl) SaveCredential(ctx context.Context, userID, email, password, imapHost, smtpHost string) error {
	// Encrypt password using AES-256-GCM
	encryptedPassword, err := infra.Encrypt(password, []byte(s.config.AESSecretKey))
	if err != nil {
		return fmt.Errorf("failed to encrypt password: %w", err)
	}

	// Use provided hosts or fallback to config defaults
	if imapHost == "" {
		imapHost = s.config.IMAPHost
	}
	if smtpHost == "" {
		smtpHost = s.config.SMTPHost
	}

	// Create EmailCredential entity
	cred := &domain.EmailCredential{
		UserID:            userID,
		EmailAddress:      email,
		EncryptedPassword: encryptedPassword,
		IMAPHost:          imapHost,
		SMTPHost:          smtpHost,
		CreatedAt:         time.Now(),
	}

	// Save to repository
	if err := s.emailRepo.Create(ctx, cred); err != nil {
		return fmt.Errorf("failed to save credentials: %w", err)
	}

	return nil
}

// SendFollowUpByAutomation sends a follow-up email based on automation ID
func (s *EmailServiceImpl) SendFollowUpByAutomation(ctx context.Context, automationID string) error {
	// Get followup rule by ID
	automation, err := s.followupRepo.GetByID(ctx, automationID)
	if err != nil {
		return fmt.Errorf("failed to get followup rule: %w", err)
	}

	// Get email credential for user
	cred, err := s.emailRepo.GetByUserID(ctx, automation.UserID)
	if err != nil {
		return fmt.Errorf("failed to get email credentials: %w", err)
	}

	// Decrypt password
	password, err := s.DecryptPassword(cred.EncryptedPassword)
	if err != nil {
		return fmt.Errorf("failed to decrypt password: %w", err)
	}

	// Compose email body with ticket info (using available data from automation)
	subject := fmt.Sprintf("Follow-up: %s", automation.JiraTicketKey)
	body := automation.EmailBody
	messageId, _ := generateMessageID(cred.EmailAddress)

	// Connect to SMTP (STARTTLS)
	recipients := []string{automation.To}
	if err := s.sendEmail(cred.EmailAddress, password, cred.SMTPHost, subject, body, messageId, recipients); err != nil {
		return fmt.Errorf("failed to send email: %w", err)
	}

	// Create EmailThread record
	thread := &domain.EmailThread{
		ID:            uuid.NewString(), // Will be generated by repository
		UserID:        automation.UserID,
		AutomationID:  automation.ID,
		GmailThreadID: messageId, // Store the generated Message-ID
		TicketID:      automation.JiraTicketID,
		Status:        domain.EmailThreadStatusOpen,
		Body:          automation.EmailBody, // Store the sent email body
		LastSyncedAt:  time.Now(),
	}

	if err := s.threadRepo.Create(ctx, thread); err != nil {
		return fmt.Errorf("failed to create email thread: %w", err)
	}

	// Increment execution count after successful email send
	automation.ExecutionCount++

	// Update automation last run time
	now := time.Now()
	automation.LastRunAt = &now

	// Check if followup should be marked as expired
	isExpired := automation.ExecutionCount >= automation.Repeat ||
		now.After(automation.ExpireDateTime)

	if isExpired {
		automation.Status = domain.FollowupStatusExpired
	}

	// Update the followup with new execution count and status
	if err := s.followupRepo.Update(ctx, automation); err != nil {
		return fmt.Errorf("failed to update followup: %w", err)
	}

	return nil
}

// PollInbox polls IMAP inbox for replies
func (s *EmailServiceImpl) PollInbox(ctx context.Context) error {
	log.Println("Starting reply detection - polling inbox for replies...")

	// Get all active followup rules
	activeFollowups, err := s.followupRepo.GetActiveRules(ctx)
	if err != nil {
		log.Printf("Failed to get active followups: %v", err)
		return fmt.Errorf("failed to get active followups: %w", err)
	}

	// Group followups by user to avoid redundant credential lookups
	userAutomations := make(map[string][]*domain.Followup)
	for _, automation := range activeFollowups {
		userAutomations[automation.UserID] = append(userAutomations[automation.UserID], automation)
	}

	log.Printf("Processing %d users with active followups", len(userAutomations))

	// Process each user's inbox
	for userID, automations := range userAutomations {
		if err := s.processUserInbox(ctx, userID, automations); err != nil {
			// Log error but continue processing other users
			log.Printf("Error processing user %s inbox: %v", userID, err)
		}
	}

	log.Println("Reply detection cycle completed")
	return nil
}

// processUserInbox processes a single user's inbox for replies
func (s *EmailServiceImpl) processUserInbox(ctx context.Context, userID string, automations []*domain.Followup) error {
	// Get email credential
	cred, err := s.emailRepo.GetByUserID(ctx, userID)
	if err != nil {
		return fmt.Errorf("failed to get credentials: %w", err)
	}

	// Decrypt password
	password, err := s.DecryptPassword(cred.EncryptedPassword)
	if err != nil {
		return fmt.Errorf("failed to decrypt password: %w", err)
	}

	// Connect to IMAP
	imapClient, err := s.connectIMAP(cred.IMAPHost, cred.EmailAddress, password)
	log.Println("connected to user")
	if err != nil {
		return fmt.Errorf("failed to connect to IMAP: %w", err)
	}
	defer imapClient.Close()

	// Select INBOX
	mbox, err := imapClient.Select("INBOX", false)
	if err != nil {
		return fmt.Errorf("failed to select INBOX: %w", err)
	}

	// Fetch unseen messages
	if mbox.Messages == 0 {
		return nil // No messages to process
	}

	// Search for unseen messages
	criteria := imap.NewSearchCriteria()
	criteria.WithoutFlags = []string{imap.SeenFlag}
	ids, err := imapClient.Search(criteria)
	if err != nil {
		return fmt.Errorf("failed to search messages: %w", err)
	}

	if len(ids) == 0 {
		log.Println("no reply messsage")
		return nil // No unseen messages
	}

	// Fetch message headers for thread matching
	seqset := new(imap.SeqSet)
	seqset.AddNum(ids...)

	messages := make(chan *imap.Message, len(ids))
	err = imapClient.Fetch(seqset, []imap.FetchItem{imap.FetchRFC822, imap.FetchEnvelope}, messages)
	if err != nil {
		return fmt.Errorf("failed to fetch messages: %w", err)
	}

	// Process messages and match to threads
	for msg := range messages {
		if err := s.processMessage(ctx, msg, userID); err != nil {
			log.Printf("Error processing message: %v", err)
		}
	}

	return nil
}

// extractEmailBodyWithMIME extracts the plain text body from an IMAP message using MIME parsing
func extractEmailBodyWithMIME(msg *imap.Message) (string, error) {
	// Get the RFC822 content (full email)
	for _, section := range msg.Body {
		// Read the section into a byte buffer
		buf := new(bytes.Buffer)
		_, err := io.Copy(buf, section)
		if err != nil {
			return "", fmt.Errorf("failed to read message section: %w", err)
		}

		// Parse the message using standard library
		emailData := buf.Bytes()

		// Split headers and body
		parts := bytes.SplitN(emailData, []byte("\r\n\r\n"), 2)
		if len(parts) < 2 {
			return "", fmt.Errorf("invalid email format")
		}

		headers := parts[0]
		body := parts[1]

		// Check Content-Type header
		contentType := "text/plain" // default
		headerLines := bytes.Split(headers, []byte("\r\n"))
		for _, line := range headerLines {
			if bytes.HasPrefix(bytes.ToLower(line), []byte("content-type:")) {
				// Extract content type value
				ctParts := bytes.SplitN(line, []byte(":"), 2)
				if len(ctParts) == 2 {
					// Parse content type to get the main type
					ct := string(bytes.TrimSpace(ctParts[1]))
					if strings.Contains(strings.ToLower(ct), "multipart/") {
						// For multipart messages, we need more complex parsing
						// For now, return the body as-is
						return string(body), nil
					} else if strings.Contains(strings.ToLower(ct), "text/plain") {
						contentType = "text/plain"
					}
				}
				break
			}
		}

		// For simple text/plain messages, return the body directly
		if contentType == "text/plain" {
			return string(body), nil
		}

		// For other content types (HTML, etc.), try to extract text
		// This is a simplified approach - for production, use a proper MIME parser
		return string(body), nil
	}

	return "", fmt.Errorf("no message sections found")
}

// processMessage processes a single message and tries to match it to a thread
func (s *EmailServiceImpl) processMessage(ctx context.Context, msg *imap.Message, userID string) error {
	log.Println("processing message")
	// Extract headers for thread matching
	var messageID, inReplyTo, references string

	if msg.Envelope != nil {
		messageID = msg.Envelope.MessageId
		inReplyTo = msg.Envelope.InReplyTo

		log.Println("threadId", inReplyTo)
		// Note: InReplyTo and References handling would be here
		// For now, we'll just use the message ID
	}

	// Extract email body using MIME parsing
	body, err := extractEmailBodyWithMIME(msg)
	if err != nil {
		log.Printf("Warning: failed to extract email body: %v", err)
		// Continue without body - non-fatal error
	}

	// Try to match message to existing thread
	thread, err := s.matchMessageToThread(ctx, messageID, inReplyTo, references, userID)
	if err != nil {
		return fmt.Errorf("failed to match message to thread: %w", err)
	}

	// If thread found, create a new reply thread record
	if thread != nil {
		// Create NEW email thread record for the reply
		replyThread := &domain.EmailThread{
			ID:            uuid.NewString(),
			UserID:        thread.UserID,
			AutomationID:  thread.AutomationID,
			GmailThreadID: messageID, // Use the reply's Message-ID
			TicketID:      thread.TicketID,
			Status:        domain.EmailThreadStatusReplied,
			Body:          body, // Parsed plain text from MIME
			LastSyncedAt:  time.Now(),
		}

		if err := s.threadRepo.Create(ctx, replyThread); err != nil {
			return fmt.Errorf("failed to create reply thread: %w", err)
		}

		log.Printf("Created new reply thread %s for automation %s", replyThread.ID, replyThread.AutomationID)

		// Update original thread to closed status (optional conversation flow)
		thread.Status = domain.EmailThreadStatusClosed
		if err := s.threadRepo.Update(ctx, thread); err != nil {
			log.Printf("Warning: failed to close original thread %s: %v", thread.ID, err)
			// Non-fatal error - reply thread was already created
		} else {
			log.Printf("Closed original thread %s", thread.ID)
		}

		// Update the associated followup to completed status
		// thread.AutomationID contains the followup ID
		followup, err := s.followupRepo.GetByID(ctx, thread.AutomationID)
		if err != nil {
			log.Printf("Warning: failed to get followup %s: %v", thread.AutomationID, err)
			// Thread was created successfully, followup update is secondary
			return nil
		}

		// Only update if followup is still ongoing
		if followup.Status == domain.FollowupStatusOngoing {
			followup.Status = domain.FollowupStatusCompleted
			if err := s.followupRepo.Update(ctx, followup); err != nil {
				log.Printf("Warning: failed to update followup status: %v", err)
				// Non-fatal error - thread was already created
			} else {
				log.Printf("Marked followup %s as completed due to reply detection", followup.ID)
			}
		}
	}

	return nil
}

// matchMessageToThread matches a message to an existing thread using headers
func (s *EmailServiceImpl) matchMessageToThread(ctx context.Context, messageID, inReplyTo, references, userID string) (*domain.EmailThread, error) {
	// Try to match by In-Reply-To header first
	if inReplyTo != "" {
		log.Println("threadId not empty and will processed")
		thread, err := s.threadRepo.GetByGmailThreadID(ctx, inReplyTo)
		if err == nil && thread != nil && thread.UserID == userID {
			log.Printf("Found thread by In-Reply-To %s", inReplyTo)
			return thread, nil
		}
		log.Printf("No suitable thread found by In-Reply-To %s", inReplyTo)
	} else {
		log.Println("threadId empty")
	}

	// Try to match by References header
	if references != "" {
		refIDs := strings.Split(references, " ")
		for _, refID := range refIDs {
			thread, err := s.threadRepo.GetByGmailThreadID(ctx, refID)
			if err == nil && thread != nil && thread.UserID == userID {
				return thread, nil
			}
		}
	}

	// Try to match by Message-ID (in case this is a direct reply)
	if messageID != "" {
		thread, err := s.threadRepo.GetByGmailThreadID(ctx, messageID)
		if err == nil && thread != nil && thread.UserID == userID {
			return thread, nil
		}
	}

	return nil, nil
}

// Helper methods

// DecryptPassword decrypts an encrypted password
func (s *EmailServiceImpl) DecryptPassword(encryptedPassword string) (string, error) {
	decrypted, err := infra.Decrypt(encryptedPassword, []byte(s.config.AESSecretKey))
	if err != nil {
		return "", fmt.Errorf("failed to decrypt password: %w", err)
	}
	return decrypted, nil
}

// connectIMAP connects to IMAP server and authenticates
func (s *EmailServiceImpl) connectIMAP(host, email, password string) (*client.Client, error) {
	// Connect to IMAP server
	imapClient, err := client.DialTLS(fmt.Sprintf("%s:993", host), &tls.Config{
		InsecureSkipVerify: false, // Use proper TLS verification in production
	})
	if err != nil {
		return nil, fmt.Errorf("failed to connect: %w", err)
	}

	// Authenticate
	if err := imapClient.Login(email, password); err != nil {
		imapClient.Close()
		return nil, fmt.Errorf("failed to authenticate: %w", err)
	}

	return imapClient, nil
}

// sendEmail sends an email using SMTP with STARTTLS
func (s *EmailServiceImpl) sendEmail(from, password, host, subject, body, messageId string, to []string) error {
	// Parse SMTP host
	parts := strings.Split(host, ":")
	smtpHost := parts[0]
	smtpPort := "587" // Default STARTTLS port

	if len(parts) > 1 {
		smtpPort = parts[1]
	}

	// Create email message
	msg := fmt.Sprintf(
		"From: %s\r\nTo: %s\r\nSubject: %s\r\nMessage-ID: %s\r\nDate: %s\r\n\r\n%s",
		from,
		strings.Join(to, ", "),
		subject,
		messageId,
		time.Now().Format(time.RFC1123Z),
		body,
	)

	// Split recipients for individual validation
	var recipients []string
	for _, addr := range to {
		if addr != "" {
			recipients = append(recipients, addr)
		}
	}

	// Connect to SMTP server and send
	auth := smtp.PlainAuth("", from, password, smtpHost)
	err := smtp.SendMail(
		fmt.Sprintf("%s:%s", smtpHost, smtpPort),
		auth,
		from,
		recipients,
		[]byte(msg),
	)

	if err != nil {
		return fmt.Errorf("failed to send email: %w", err)
	}

	return nil
}

func generateMessageID(emailFrom string) (string, error) {
	b := make([]byte, 16)
	_, err := rand.Read(b)
	if err != nil {
		return "", fmt.Errorf("failed to generate message ID: %w", err)
	}

	domain := emailFrom[strings.Index(emailFrom, "@")+1:]
	timestamp := time.Now().UnixNano()
	return fmt.Sprintf("<%d.%s@%s>", timestamp, hex.EncodeToString(b), domain), nil
}

// composeEmailBody creates the email body with Jira ticket context
func (s *EmailServiceImpl) composeEmailBodyForAutomation(automation *domain.Followup) string {
	return fmt.Sprintf(`Hello,

This is a follow-up regarding the Jira ticket: %s

Please review and take appropriate action.

Note: For detailed ticket information, please check your Jira instance directly.

Best regards`,
		automation.JiraTicketKey,
	)
}

// Legacy interface methods (for compatibility)

// RegisterCredential registers or updates email credentials
func (s *EmailServiceImpl) RegisterCredential(ctx interface{}, cred *domain.EmailCredential) error {
	contextCast, ok := ctx.(context.Context)
	if !ok {
		return fmt.Errorf("invalid context type")
	}

	if cred.EmailAddress == "" {
		return fmt.Errorf("email address is required")
	}
	// Check if credential already exists
	existingCred, err := s.emailRepo.GetByUserID(contextCast, cred.UserID)
	if err != nil {
		// Credential doesn't exist, create new one
		return s.emailRepo.Create(contextCast, cred)
	}
	// Credential exists, update it
	cred.CreatedAt = existingCred.CreatedAt // Preserve creation time
	return s.emailRepo.Update(contextCast, cred)
}

// GetCredential retrieves email credentials for a user
func (s *EmailServiceImpl) GetCredential(ctx interface{}, userID string) (*domain.EmailCredential, error) {
	contextCast, ok := ctx.(context.Context)
	if !ok {
		return nil, fmt.Errorf("invalid context type")
	}
	return s.emailRepo.GetByUserID(contextCast, userID)
}

// SendFollowUp sends a follow-up email
func (s *EmailServiceImpl) SendFollowUp(ctx interface{}, threadID, subject, body string, recipients []string) error {
	// This is a placeholder for the legacy interface method
	return fmt.Errorf("not implemented: use SendFollowUpByAutomation instead")
}

// CheckForReplies checks IMAP for replies to sent emails
func (s *EmailServiceImpl) CheckForReplies(ctx interface{}) error {
	contextCast, ok := ctx.(context.Context)
	if !ok {
		return fmt.Errorf("invalid context type")
	}
	return s.PollInbox(contextCast)
}
